travis:
  secure:
    BINSTAR_TOKEN: VQFE8wK0qSBAguD4hKyrDtKbFFLiQf3PHZUMPRBBThB68NiqIdHPvcQRvSBXQMavh9KDebW30bNqkMnG5dQzmk3DLlZzh6JuLX5WxtwKoDlw83fe+3UBiKOm2zQGP8S5NCy2LWRO99ZGjlwMSztd3T39jkiB3OYl5Jf9k5Eeydr6EKISP6SNeADe6vq7H424N6flTKTGVQ4b1HZcN7UVIdimmNeNaIrgSuSf4fq57218bR7cXhlCJSsVpoi0UZO09kz5oyz+35oHG6v5wpef5+yPoWok1JWXi+P+yhpSoa/kr+ql+/qe5O9C/dJiZSBlIEeVwJZH+WuaQqi5WpuZElxNJMr5VJf7PhvKhlD9hYDNak0b79y1yjfsalvkhQQTMDjHQ+oFQNWIHedkIZFdGI4uKz7+ruQFbB7nAb9Z3lrmxjRWn4YCJSGyvehGieT4HiBji7FtRRMk+B2kmmv752TlO03WG/LNQqVtithwzPni/1YXCXsLS/noNkE/oon3k/b772p9Y6XdfHmVn9ViOHWJ5wtX+WQL9T+UAIQtUUt+SwrWlPKFDK0ZcmWK2Ny9pmgTbcNmxvxwulJQLwjfV3VHB4Ub6gMK28P+ZJiqJsQpgJojCgY6Iprd1Cdq9xLjP4bCSjjFmyzAsNXosbsPnBuRdlqpJz57anKkjT/p9sU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
